version: 2
jobs:
  test_debug:
    docker:
      - image: tschijnmo/drudge:corebase
    steps:
      - run: |
          git clone --recurse-submodules https://github.com/tschijnmo/libparenth.git
          mkdir cmake-test-debug
          cd cmake-test-debug
          cmake -DCMAKE_BUILD_TYPE=debug ../libparenth
          make
          ./test/testmain

  test_release:
    docker:
      - image: tschijnmo/gccpython:latest
    steps:
      - run: |
          git clone --recurse-submodules https://github.com/tschijnmo/libparenth.git
          mkdir cmake-test-release
          cd cmake-test-release
          cmake -DCMAKE_BUILD_TYPE=release ../libparenth
          make
          ./test/testmain

workflows:
  version: 2
  tests:
    jobs:
      - test_debug
      - test_release

